FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Portas: 8001=auth 8002=company 8003=catalog 8004=order 8005=payment
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]