"""seed do catálogo de demonstração da Burger House (ORD-117)

86 produtos em 11 categorias, gerados a partir de
docs/exemples/categorias-produtos-bh/catalogo_burger_house.md. Reaproveita as
categorias Lanches/Combos/Bebidas/Sobremesas (ids 1-4) já criadas por
seed_initial.py — só as 7 categorias que não existem no seed original ganham
id novo (101-107). Produtos usam ids 1000-1085, fora da faixa do seed
original (ids 1-25) — mesmo padrão de INSERT IGNORE idempotente. Imagens
não entram aqui (ver scripts/seed_demo_images.py) — migration não faz I/O
de rede.

Revision ID: 20260824_0930
Revises: 20260807_1400
Create Date: 2026-08-24 09:30:00
"""
from alembic import op

revision = "20260824_0930"
down_revision = "20260807_1400"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── categorias ───────────────────────────────────────────────────────────
    op.execute("""
        INSERT IGNORE INTO categories (id, company_id, name, active) VALUES
        (1, 1, 'Lanches', 1),
        (2, 1, 'Combos', 1),
        (4, 1, 'Sobremesas', 1),
        (3, 1, 'Bebidas', 1),
        (101, 1, 'Porções', 1),
        (102, 1, 'Saladas', 1),
        (103, 1, 'Molhos', 1),
        (104, 1, 'Promoções', 1),
        (105, 1, 'Kids', 1),
        (106, 1, 'Vegano', 1),
        (107, 1, 'Especiais', 1)
    """)

    # ── produtos ─────────────────────────────────────────────────────────────
    op.execute("""
        INSERT IGNORE INTO products
          (id, company_id, category_id, name, description, description_long,
           price, calories, sku, tags, sort_order, active) VALUES
        (1000, 1, 1, 'Classic Cheddar Burger', 'Blend bovino 160g, cheddar, alface, tomate e molho da casa no pão brioche.', 'O clássico que não sai do cardápio: blend bovino 160g grelhado no ponto, fatia generosa de cheddar derretido, alface americana crocante, tomate fresco e o molho especial da casa, tudo montado em pão brioche amanteigado e tostado na chapa.', 28.9, 620, 'BH-LAN-001', '["mais vendido", "clássico"]', 0, 1),
        (1001, 1, 1, 'Bacon Smash Duplo', 'Dois smash burgers 90g, bacon crocante, cheddar e cebola caramelizada.', 'Duas carnes prensadas na chapa (smash) para máxima crosta, intercaladas com fatias de bacon bem crocante, queijo cheddar duplo e cebola caramelizada lentamente, no pão brioche selado na manteiga.', 34.9, 780, 'BH-LAN-002', '["bestseller", "defumado"]', 1, 1),
        (1002, 1, 1, 'Cogumelos & Suíço', 'Blend 160g, cogumelos salteados na manteiga e queijo suíço com maionese trufada.', 'Blend bovino grelhado, cogumelos frescos salteados na manteiga e alho, queijo suíço derretido e um toque de maionese trufada, para quem gosta de um burger mais sofisticado.', 32.9, 690, 'BH-LAN-003', '["gourmet"]', 2, 1),
        (1003, 1, 1, 'BBQ Onion Crispy', 'Blend 160g, onion rings crocantes, molho barbecue defumado e queijo prato.', 'Burger robusto com blend 160g, anéis de cebola empanados e crocantes, queijo prato derretido e generosa quantidade do nosso molho barbecue defumado artesanal.', 33.9, 740, 'BH-LAN-004', '["crocante", "defumado"]', 3, 1),
        (1004, 1, 1, 'Frango Crispy', 'Filé de frango empanado crocante, maionese de ervas e picles.', 'Filé de peito de frango empanado e frito até ficar bem crocante por fora e suculento por dentro, com maionese de ervas frescas e picles artesanais para dar acidez.', 29.9, 640, 'BH-LAN-005', '["frango", "crocante"]', 4, 1),
        (1005, 1, 1, 'Costela Desfiada BBQ', 'Pão australiano, costela bovina desfiada por 12h e molho barbecue.', 'Costela bovina cozida lentamente por 12 horas até desfiar, queijo cheddar derretido e molho barbecue caseiro, montado em pão australiano levemente adocicado.', 36.9, 810, 'BH-LAN-006', '["premium", "defumado"]', 5, 1),
        (1006, 1, 1, 'Burger da Casa', 'Blend especial da casa, queijo coalho grelhado e geleia de pimenta.', 'Nossa receita autoral: blend bovino temperado com especiarias da casa, queijo coalho grelhado na chapa e geleia de pimenta artesanal, equilibrando doce e picante.', 31.9, 700, 'BH-LAN-007', '["autoral"]', 6, 1),
        (1007, 1, 1, 'Picanha Burger', 'Blend de picanha, catupiry e cebola crispy.', 'Blend feito com corte nobre de picanha, queijo catupiry cremoso e cebola crispy, para os apaixonados por um sabor mais encorpado.', 38.9, 760, 'BH-LAN-008', '["premium"]', 7, 1),
        (1008, 1, 1, 'Fish Burger', 'Filé de peixe empanado, molho tártaro e alface americana.', 'Filé de peixe branco empanado e frito na hora, com molho tártaro caseiro e alface americana fresca, uma opção mais leve dentro dos lanches.', 30.9, 580, 'BH-LAN-009', '["peixe"]', 8, 1),
        (1009, 1, 1, 'Egg Bacon Burger', 'Blend 160g, ovo frito, bacon crocante e cheddar.', 'Blend bovino grelhado coberto por ovo frito com a gema mole, bacon crocante e queijo cheddar derretido, um clássico reforçado para quem tem fome de verdade.', 33.9, 770, 'BH-LAN-010', '["clássico"]', 9, 1),
        (1010, 1, 2, 'Combo Clássico', 'Classic Cheddar Burger + Batata Frita Crocante + Refrigerante Lata.', 'O combo mais pedido da casa: Classic Cheddar Burger acompanhado de porção individual de Batata Frita Crocante e um refrigerante em lata gelado.', 41.7, 1180, 'BH-COM-001', '["combo", "economia"]', 0, 1),
        (1011, 1, 2, 'Combo Bacon Duplo', 'Bacon Smash Duplo + Onion Rings + Refrigerante Lata.', 'Para quem não abre mão de sabor: Bacon Smash Duplo com uma porção de Onion Rings Empanados e refrigerante em lata.', 52.7, 1360, 'BH-COM-002', '["combo"]', 1, 1),
        (1012, 1, 2, 'Combo Frango Crispy', 'Frango Crispy + Batata Frita Crocante + Suco Natural.', 'Frango Crispy acompanhado de Batata Frita Crocante e um Suco Natural de Laranja 400ml, uma combinação equilibrada entre crocância e frescor.', 43.7, 1150, 'BH-COM-003', '["combo"]', 2, 1),
        (1013, 1, 2, 'Combo Costela BBQ', 'Costela Desfiada BBQ + Batata Rústica com Alecrim + Refrigerante Lata.', 'Costela Desfiada BBQ, servida com Batata Rústica com Alecrim e refrigerante em lata, ideal para quem busca uma refeição mais completa.', 57.7, 1350, 'BH-COM-004', '["combo", "premium"]', 3, 1),
        (1014, 1, 2, 'Combo Picanha', 'Picanha Burger + Anéis de Calabresa Acebolada + Refrigerante Lata.', 'Picanha Burger com Anéis de Calabresa Acebolada e refrigerante em lata, combo pensado para quem gosta de sabores mais marcantes.', 58.7, 1330, 'BH-COM-005', '["combo", "premium"]', 4, 1),
        (1015, 1, 2, 'Combo Fish', 'Fish Burger + Salada Verde com Nozes e Mel (mini) + Suco Natural.', 'Fish Burger acompanhado de uma versão individual da Salada Verde com Nozes e Mel e Suco Natural de Abacaxi com Hortelã, opção mais leve entre os combos.', 40.7, 1020, 'BH-COM-006', '["combo", "leve"]', 5, 1),
        (1016, 1, 2, 'Combo Casal', '2 Burgers à escolha + Batata Frita Grande + 2 Refrigerantes Lata.', 'Dois lanches à escolha entre os Lanches do cardápio, acompanhados de uma porção grande de Batata Frita Crocante para dividir e dois refrigerantes em lata.', 79.9, 1900, 'BH-COM-007', '["combo", "para compartilhar"]', 6, 1),
        (1017, 1, 2, 'Combo Vegano', 'Burger Vegano de Grão-de-Bico + Batata Rústica Vegana + Suco Natural.', 'Burger Vegano de Grão-de-Bico com Batata Rústica Vegana com Ervas e Suco Natural de Abacaxi com Hortelã, combo 100% vegano.', 46.7, 1080, 'BH-COM-008', '["combo", "vegano"]', 7, 1),
        (1018, 1, 4, 'Petit Gateau', 'Bolo de chocolate quente com recheio cremoso e sorvete de baunilha.', 'Bolinho de chocolate assado na hora, com centro cremoso que escorre ao cortar, servido quente com uma bola de sorvete de baunilha.', 18.9, 480, 'BH-SOB-001', '["chocolate", "clássico"]', 0, 1),
        (1019, 1, 4, 'Brownie de Nozes com Sorvete', 'Brownie de chocolate meio amargo com nozes, sorvete de creme e calda quente.', 'Brownie denso de chocolate meio amargo com pedaços de nozes, servido morno com uma bola de sorvete de creme e calda de chocolate quente.', 16.9, 520, 'BH-SOB-002', '["chocolate"]', 1, 1),
        (1020, 1, 4, 'Cheesecake de Frutas Vermelhas', 'Cheesecake cremoso com calda artesanal de frutas vermelhas.', 'Base amanteigada, recheio cremoso de cream cheese e cobertura de calda artesanal de frutas vermelhas frescas.', 17.9, 410, 'BH-SOB-003', '["cremoso"]', 2, 1),
        (1021, 1, 4, 'Milk-Shake de Chocolate', 'Milk-shake cremoso de chocolate com chantilly.', 'Sorvete de chocolate batido com leite integral até ficar bem cremoso, finalizado com chantilly e calda de chocolate.', 16.9, 450, 'BH-SOB-004', '["milk-shake", "gelado"]', 3, 1),
        (1022, 1, 4, 'Milk-Shake de Morango', 'Milk-shake cremoso de morango com chantilly.', 'Sorvete de morango batido com leite integral e pedaços de morango fresco, finalizado com chantilly.', 16.9, 430, 'BH-SOB-005', '["milk-shake", "gelado"]', 4, 1),
        (1023, 1, 4, 'Sundae de Caramelo com Amendoim', 'Sorvete de creme, calda de caramelo e amendoim triturado.', 'Bolas de sorvete de creme cobertas com calda de caramelo artesanal e finalizadas com amendoim triturado torrado.', 14.9, 390, 'BH-SOB-006', '["gelado"]', 5, 1),
        (1024, 1, 4, 'Torta de Limão', 'Torta cremosa de limão com base crocante e merengue maçaricado.', 'Base crocante amanteigada, recheio cremoso de limão siciliano e cobertura de merengue levemente maçaricado.', 15.9, 380, 'BH-SOB-007', '["cítrico"]', 6, 1),
        (1025, 1, 4, 'Churros Recheados com Doce de Leite', 'Churros crocantes por fora, recheados com doce de leite quente.', 'Churros fritos na hora, crocantes por fora e macios por dentro, recheados com doce de leite quente e polvilhados com açúcar e canela.', 14.9, 410, 'BH-SOB-008', '["quentinho"]', 7, 1),
        (1026, 1, 3, 'Coca-Cola Lata 350ml', 'Refrigerante Coca-Cola gelado, lata 350ml.', 'Refrigerante Coca-Cola tradicional, servido bem gelado, lata de 350ml.', 6.9, 140, 'BH-BEB-001', '["refrigerante", "gelado"]', 0, 1),
        (1027, 1, 3, 'Guaraná Antarctica Lata 350ml', 'Refrigerante de guaraná gelado, lata 350ml.', 'Refrigerante sabor guaraná, servido bem gelado, lata de 350ml.', 6.9, 140, 'BH-BEB-002', '["refrigerante", "gelado"]', 1, 1),
        (1028, 1, 3, 'Coca-Cola Zero Lata 350ml', 'Refrigerante Coca-Cola Zero açúcar, lata 350ml.', 'Versão sem açúcar da Coca-Cola tradicional, servida gelada, lata de 350ml.', 6.9, 1, 'BH-BEB-003', '["refrigerante", "zero açúcar"]', 2, 1),
        (1029, 1, 3, 'Suco Natural de Laranja 400ml', 'Suco de laranja natural, feito na hora, 400ml.', 'Suco de laranja espremido na hora, sem adição de açúcar, servido gelado em copo de 400ml.', 9.9, 180, 'BH-BEB-004', '["suco natural", "sem álcool"]', 3, 1),
        (1030, 1, 3, 'Suco Natural de Abacaxi com Hortelã 400ml', 'Suco natural de abacaxi com hortelã fresca, 400ml.', 'Suco de abacaxi natural batido com folhas de hortelã fresca, refrescante e servido bem gelado.', 9.9, 160, 'BH-BEB-005', '["suco natural", "refrescante"]', 4, 1),
        (1031, 1, 3, 'Chá Gelado de Pêssego 400ml', 'Chá gelado sabor pêssego, 400ml.', 'Chá preto gelado com sabor natural de pêssego, levemente adoçado, servido com gelo.', 8.9, 120, 'BH-BEB-006', '["chá gelado"]', 5, 1),
        (1032, 1, 3, 'Red Bull Energy Drink 250ml', 'Energético Red Bull, lata 250ml.', 'Bebida energética tradicional, lata de 250ml, servida gelada.', 13.9, 115, 'BH-BEB-007', '["energético"]', 6, 1),
        (1033, 1, 3, 'Água Mineral 500ml', 'Água mineral, com ou sem gás, 500ml.', 'Água mineral natural, disponível com ou sem gás, garrafa de 500ml.', 5.9, 0, 'BH-BEB-008', '["água"]', 7, 1),
        (1034, 1, 3, 'Chopp Pilsen 300ml', 'Chopp Pilsen gelado, copo 300ml. Bebida alcoólica.', 'Chopp estilo Pilsen, leve e refrescante, servido bem gelado em copo de 300ml. Venda proibida para menores de 18 anos.', 9.9, 150, 'BH-BEB-009', '["bebida alcoólica", "cerveja", "chopp"]', 8, 1),
        (1035, 1, 3, 'Cerveja Artesanal IPA 355ml', 'Cerveja artesanal estilo IPA, garrafa 355ml. Bebida alcoólica.', 'Cerveja artesanal estilo IPA, aromática e com amargor acentuado, garrafa de 355ml. Venda proibida para menores de 18 anos.', 16.9, 210, 'BH-BEB-010', '["bebida alcoólica", "cerveja artesanal"]', 9, 1),
        (1036, 1, 3, 'Caipirinha de Limão', 'Caipirinha tradicional de limão com cachaça. Bebida alcoólica.', 'Drink clássico brasileiro feito com cachaça, limão fresco, açúcar e gelo. Venda proibida para menores de 18 anos.', 19.9, 220, 'BH-BEB-011', '["drink", "bebida alcoólica", "coquetel"]', 10, 1),
        (1037, 1, 3, 'Gin Tônica com Frutas Vermelhas', 'Gin tônica com frutas vermelhas frescas. Bebida alcoólica.', 'Drink refrescante de gin com água tônica, gelo e frutas vermelhas frescas. Venda proibida para menores de 18 anos.', 24.9, 190, 'BH-BEB-012', '["drink", "bebida alcoólica", "coquetel"]', 11, 1),
        (1038, 1, 101, 'Batata Frita Crocante', 'Porção de batata frita crocante, servida quentinha.', 'Batatas selecionadas, fritas até ficarem bem crocantes por fora e macias por dentro, temperadas com sal na medida certa.', 19.9, 420, 'BH-POR-001', '["porção", "crocante"]', 0, 1),
        (1039, 1, 101, 'Batata Rústica com Alecrim', 'Batata rústica assada com alecrim fresco e páprica.', 'Batatas com casca, assadas com alecrim fresco, páprica e azeite, para um sabor mais rústico e aromático.', 22.9, 440, 'BH-POR-002', '["porção", "gourmet"]', 1, 1),
        (1040, 1, 101, 'Onion Rings Empanados', 'Anéis de cebola empanados e fritos até ficarem crocantes.', 'Anéis de cebola roxa empanados em farinha temperada e fritos até dourar, servidos com molho à parte.', 24.9, 460, 'BH-POR-003', '["porção", "crocante"]', 2, 1),
        (1041, 1, 101, 'Polenta Frita com Molho', 'Palitos de polenta frita, crocantes por fora, com molho da casa.', 'Palitos de polenta cremosa, empanados e fritos até dourar, servidos com molho especial da casa.', 21.9, 390, 'BH-POR-004', '["porção"]', 3, 1),
        (1042, 1, 101, 'Frango à Passarinho', 'Petiscos de frango temperados e fritos, com alho crocante.', 'Pedaços de frango temperados com alho e limão, fritos até ficarem crocantes por fora e suculentos por dentro, finalizados com alho frito.', 28.9, 520, 'BH-POR-005', '["porção", "para compartilhar"]', 4, 1),
        (1043, 1, 101, 'Isca de Peixe Empanada', 'Iscas de peixe empanadas e fritas, com molho tártaro.', 'Iscas de filé de peixe branco empanadas artesanalmente e fritas na hora, acompanhadas de molho tártaro.', 29.9, 480, 'BH-POR-006', '["porção", "peixe"]', 5, 1),
        (1044, 1, 101, 'Nachos com Queijo e Guacamole', 'Nachos crocantes com queijo derretido e guacamole fresco.', 'Chips de milho crocantes cobertos com queijo derretido, servidos com guacamole fresco e pico de gallo.', 26.9, 560, 'BH-POR-007', '["porção", "para compartilhar"]', 6, 1),
        (1045, 1, 101, 'Anéis de Calabresa Acebolada', 'Calabresa fatiada e grelhada com cebola.', 'Calabresa artesanal fatiada, grelhada com cebola até dourar, servida bem quente.', 23.9, 470, 'BH-POR-008', '["porção", "defumado"]', 7, 1),
        (1046, 1, 101, 'Mandioca Frita Crocante', 'Mandioca frita, crocante por fora e macia por dentro.', 'Mandioca cozida no ponto certo e depois frita até ficar bem crocante por fora, mantendo o interior macio.', 20.9, 410, 'BH-POR-009', '["porção"]', 8, 1),
        (1047, 1, 102, 'Salada Caesar com Frango Grelhado', 'Alface romana, frango grelhado, croutons e molho caesar.', 'Alface romana fresca, tiras de frango grelhado, croutons crocantes, lascas de parmesão e molho caesar tradicional.', 26.9, 380, 'BH-SAL-001', '["salada", "com frango"]', 0, 1),
        (1048, 1, 102, 'Salada Caprese', 'Tomate, mussarela de búfala, manjericão fresco e azeite.', 'Fatias de tomate maduro, mussarela de búfala, folhas de manjericão fresco, regados com azeite extra virgem e redução de balsâmico.', 22.9, 290, 'BH-SAL-002', '["salada", "vegetariano"]', 1, 1),
        (1049, 1, 102, 'Salada Verde com Nozes e Mel', 'Mix de folhas verdes, nozes crocantes e vinagrete de mel.', 'Mix de folhas verdes frescas, nozes levemente torradas, tomate cereja e vinagrete de mel e mostarda.', 24.9, 310, 'BH-SAL-003', '["salada", "crocante"]', 2, 1),
        (1050, 1, 102, 'Salada de Quinoa com Legumes Grelhados', 'Quinoa, legumes grelhados e folhas frescas.', 'Quinoa cozida, legumes grelhados da estação e folhas verdes frescas, temperada com azeite e limão.', 25.9, 340, 'BH-SAL-004', '["salada", "vegano"]', 3, 1),
        (1051, 1, 102, 'Salada Tropical com Frango e Manga', 'Folhas verdes, frango grelhado, manga e castanhas.', 'Mix de folhas verdes, tiras de frango grelhado, cubos de manga fresca e castanha de caju, com molho cítrico leve.', 27.9, 360, 'BH-SAL-005', '["salada", "com frango"]', 4, 1),
        (1052, 1, 102, 'Salada de Grão-de-Bico com Rúcula', 'Grão-de-bico, rúcula fresca, tomate seco e azeite.', 'Grão-de-bico temperado, rúcula fresca, tomate seco e cebola roxa, finalizada com azeite extra virgem.', 23.9, 320, 'BH-SAL-006', '["salada", "vegano"]', 5, 1),
        (1053, 1, 103, 'Molho Barbecue Defumado', 'Molho barbecue artesanal com toque defumado.', 'Molho barbecue produzido na casa, com toque defumado e leve doçura, ideal para acompanhar lanches e porções.', 5.9, 60, 'BH-MOL-001', '["molho", "acompanhamento"]', 0, 1),
        (1054, 1, 103, 'Molho Cheddar Cremoso', 'Molho cremoso de cheddar para acompanhar porções.', 'Molho cremoso à base de queijo cheddar, perfeito para mergulhar batatas e petiscos.', 6.9, 90, 'BH-MOL-002', '["molho", "cremoso"]', 1, 1),
        (1055, 1, 103, 'Maionese Trufada', 'Maionese artesanal com azeite trufado.', 'Maionese caseira preparada com azeite trufado, para dar um toque especial a lanches e porções.', 5.9, 80, 'BH-MOL-003', '["molho", "gourmet"]', 2, 1),
        (1056, 1, 103, 'Molho Especial da Casa', 'Receita exclusiva da casa, levemente picante.', 'Molho autoral da casa, combinação de especiarias e um leve toque picante, usado em vários lanches do cardápio.', 5.9, 70, 'BH-MOL-004', '["molho", "autoral"]', 3, 1),
        (1057, 1, 103, 'Molho Tártaro', 'Molho tártaro caseiro, ideal para peixes e frituras.', 'Molho tártaro preparado com maionese, picles e ervas frescas, harmoniza especialmente bem com peixe e frituras.', 5.9, 75, 'BH-MOL-005', '["molho"]', 4, 1),
        (1058, 1, 103, 'Molho de Pimenta Artesanal', 'Molho de pimenta artesanal, picância média.', 'Molho de pimenta produzido artesanalmente, com picância moderada e sabor equilibrado.', 4.9, 20, 'BH-MOL-006', '["molho", "picante"]', 5, 1),
        (1059, 1, 103, 'Molho Ranch', 'Molho ranch cremoso com ervas finas.', 'Molho cremoso à base de iogurte e ervas finas, no estilo ranch americano.', 6.9, 85, 'BH-MOL-007', '["molho", "cremoso"]', 6, 1),
        (1060, 1, 104, 'Terça do Burger', 'Classic Cheddar Burger + Batata + Refri por um preço especial às terças.', 'Toda terça-feira, o Classic Cheddar Burger acompanhado de Batata Frita Crocante e Refrigerante Lata sai por um preço promocional.', 29.9, 1180, 'BH-PRM-001', '["promoção", "oferta", "terça"]', 0, 1),
        (1061, 1, 104, 'Quarta é Dia de Combo Duplo', '2 Combos Clássicos pelo preço promocional às quartas-feiras.', 'Todas as quartas-feiras, leve dois Combos Clássicos completos por um valor promocional especial.', 69.9, 2360, 'BH-PRM-002', '["promoção", "oferta", "quarta"]', 1, 1),
        (1062, 1, 104, 'Happy Hour Chopp + Porção', 'Chopp Pilsen + Onion Rings em oferta no happy hour.', 'Das 17h às 19h, Chopp Pilsen 300ml acompanhado de uma porção de Onion Rings Empanados por preço promocional. Bebida alcoólica, venda proibida para menores de 18 anos.', 24.9, 610, 'BH-PRM-003', '["promoção", "happy hour", "bebida alcoólica"]', 2, 1),
        (1063, 1, 104, 'Sexta do Bacon', 'Bacon Smash Duplo com desconto especial às sextas-feiras.', 'Toda sexta-feira, o Bacon Smash Duplo sai com desconto especial, sem acompanhamento incluso.', 27.9, 780, 'BH-PRM-004', '["promoção", "oferta", "sexta"]', 3, 1),
        (1064, 1, 104, 'Domingo em Família', 'Combo Casal com sobremesa cortesia aos domingos.', 'Aos domingos, o Combo Casal vem acompanhado de uma sobremesa à escolha por conta da casa.', 79.9, 2380, 'BH-PRM-005', '["promoção", "família", "domingo"]', 4, 1),
        (1065, 1, 104, 'Combo Estudante', 'Frango Crispy + Refrigerante com desconto mediante carteirinha.', 'Frango Crispy acompanhado de Refrigerante Lata por preço promocional para estudantes mediante apresentação de carteirinha válida.', 26.9, 780, 'BH-PRM-006', '["promoção", "estudante"]', 5, 1),
        (1066, 1, 105, 'Mini Burger Kids', 'Versão mini do burger clássico, tamanho ideal para crianças.', 'Mini blend bovino, queijo derretido e pão macio, uma versão reduzida e balanceada pensada para o público infantil.', 19.9, 380, 'BH-KID-001', '["kids"]', 0, 1),
        (1067, 1, 105, 'Nuggets de Frango Kids (6un)', 'Seis unidades de nuggets de frango crocantes.', 'Seis nuggets de frango empanados e fritos até dourar, tamanho ideal para o prato infantil.', 18.9, 350, 'BH-KID-002', '["kids", "frango"]', 1, 1),
        (1068, 1, 105, 'Mini Fish Kids', 'Mini filé de peixe empanado, porção infantil.', 'Mini filé de peixe empanado e frito, porção reduzida pensada especialmente para crianças.', 19.9, 340, 'BH-KID-003', '["kids", "peixe"]', 2, 1),
        (1069, 1, 105, 'Combo Kids Mini Burger', 'Mini Burger Kids + Suco + brinde surpresa.', 'Mini Burger Kids acompanhado de Suco Natural e um brinde surpresa, combo completo para a criançada.', 24.9, 520, 'BH-KID-004', '["kids", "combo"]', 3, 1),
        (1070, 1, 105, 'Macarrão com Molho Sugo Kids', 'Porção infantil de macarrão ao molho sugo.', 'Macarrão al dente com molho sugo caseiro, porção pensada para o tamanho e o gosto das crianças.', 17.9, 400, 'BH-KID-005', '["kids"]', 4, 1),
        (1071, 1, 105, 'Batata Frita Kids', 'Porção infantil de batata frita crocante.', 'Porção reduzida de batata frita crocante, tamanho ideal para acompanhar os pratos infantis.', 12.9, 280, 'BH-KID-006', '["kids", "porção"]', 5, 1),
        (1072, 1, 106, 'Burger Vegano de Grão-de-Bico', 'Hambúrguer vegano de grão-de-bico com legumes assados.', 'Hambúrguer 100% vegetal à base de grão-de-bico e legumes assados, temperado com especiarias, servido no pão vegano.', 29.9, 480, 'BH-VEG-001', '["vegano"]', 0, 1),
        (1073, 1, 106, 'Burger Vegano de Cogumelos e Quinoa', 'Hambúrguer vegano de cogumelos e quinoa com molho vegano.', 'Hambúrguer vegetal feito com cogumelos, quinoa e ervas frescas, acompanhado de molho especial vegano.', 31.9, 460, 'BH-VEG-002', '["vegano"]', 1, 1),
        (1074, 1, 106, 'Batata Rústica Vegana com Ervas', 'Batata rústica assada com ervas, 100% vegana.', 'Batatas com casca assadas com azeite e ervas frescas, sem nenhum ingrediente de origem animal.', 22.9, 400, 'BH-VEG-003', '["vegano", "porção"]', 2, 1),
        (1075, 1, 106, 'Salada Vegana de Grãos e Vegetais', 'Mix de grãos, vegetais frescos e vinagrete vegano.', 'Mix de grãos, legumes frescos e folhas verdes, temperado com vinagrete 100% vegetal.', 24.9, 300, 'BH-VEG-004', '["vegano", "salada"]', 3, 1),
        (1076, 1, 106, 'Milk-Shake Vegano de Banana', 'Milk-shake vegano de banana com leite de amêndoas.', 'Milk-shake cremoso de banana feito com leite de amêndoas, sem nenhum ingrediente de origem animal.', 18.9, 320, 'BH-VEG-005', '["vegano", "milk-shake"]', 4, 1),
        (1077, 1, 106, 'Nuggets Veganos de Grão-de-Bico', 'Nuggets veganos de grão-de-bico empanados e crocantes.', 'Nuggets 100% vegetais à base de grão-de-bico, empanados e fritos até ficarem crocantes por fora.', 23.9, 380, 'BH-VEG-006', '["vegano"]', 5, 1),
        (1078, 1, 106, 'Brownie Vegano sem Glúten', 'Brownie vegano e sem glúten, denso e achocolatado.', 'Brownie 100% vegetal e sem glúten, feito com farinha de arroz e chocolate 70% cacau, denso e saboroso.', 16.9, 350, 'BH-VEG-007', '["vegano", "sem glúten"]', 6, 1),
        (1079, 1, 107, 'Burger Trufado Especial', 'Blend premium, queijo brie, cogumelos e maionese trufada.', 'Blend bovino premium, queijo brie derretido, cogumelos salteados e maionese trufada, uma criação exclusiva do chef.', 44.9, 820, 'BH-ESP-001', '["especial", "premium"]', 0, 1),
        (1080, 1, 107, 'Costela no Bafo com Farofa Especial', 'Costela bovina cozida lentamente, servida com farofa especial da casa.', 'Costela bovina cozida lentamente no bafo até ficar extremamente macia, servida com farofa especial preparada na casa.', 52.9, 980, 'BH-ESP-002', '["especial", "para compartilhar"]', 1, 1),
        (1081, 1, 107, 'Tábua de Petiscos da Casa', 'Seleção de petiscos da casa para compartilhar.', 'Tábua com seleção de petiscos da casa: onion rings, nuggets, calabresa acebolada e molhos, ideal para compartilhar entre 3-4 pessoas.', 68.9, 1450, 'BH-ESP-003', '["especial", "para compartilhar"]', 2, 1),
        (1082, 1, 107, 'Burger do Chef com Brie e Damasco', 'Blend bovino, queijo brie e geleia de damasco.', 'Criação autoral do chef: blend bovino grelhado, queijo brie cremoso e geleia de damasco artesanal, equilibrando doce e salgado.', 39.9, 760, 'BH-ESP-004', '["especial", "autoral"]', 3, 1),
        (1083, 1, 107, 'Risoto de Cogumelos Selvagens', 'Risoto cremoso de cogumelos selvagens com parmesão.', 'Risoto cremoso preparado com mix de cogumelos selvagens e finalizado com lascas de parmesão.', 36.9, 540, 'BH-ESP-005', '["especial"]', 4, 1),
        (1084, 1, 107, 'Cerveja Artesanal Especial da Casa (Growler 500ml)', 'Cerveja artesanal exclusiva da casa, growler 500ml. Bebida alcoólica.', 'Receita exclusiva de cerveja artesanal da casa, servida em growler de 500ml. Venda proibida para menores de 18 anos.', 34.9, 260, 'BH-ESP-006', '["especial", "bebida alcoólica"]', 5, 1),
        (1085, 1, 107, 'Steak Sanduíche de Filé Mignon', 'Fatias de filé mignon grelhado, cebola crispy e molho especial.', 'Fatias de filé mignon grelhadas no ponto, cebola crispy e molho especial da casa, montado em pão artesanal.', 46.9, 890, 'BH-ESP-007', '["especial", "premium"]', 6, 1)
    """)

    # ── vínculos de alérgeno ─────────────────────────────────────────────────
    op.execute("""
        INSERT IGNORE INTO product_allergens (product_id, allergen_id) VALUES
        (1000, 49),
        (1000, 54),
        (1000, 58),
        (1001, 49),
        (1001, 54),
        (1001, 58),
        (1002, 49),
        (1002, 54),
        (1002, 58),
        (1003, 49),
        (1003, 54),
        (1003, 58),
        (1003, 57),
        (1004, 49),
        (1004, 54),
        (1004, 58),
        (1005, 49),
        (1005, 54),
        (1005, 58),
        (1005, 57),
        (1006, 49),
        (1006, 54),
        (1006, 58),
        (1007, 49),
        (1007, 54),
        (1007, 58),
        (1008, 49),
        (1008, 54),
        (1008, 55),
        (1009, 49),
        (1009, 54),
        (1009, 58),
        (1010, 49),
        (1010, 54),
        (1010, 58),
        (1011, 49),
        (1011, 54),
        (1011, 58),
        (1012, 49),
        (1012, 54),
        (1012, 58),
        (1013, 49),
        (1013, 54),
        (1013, 58),
        (1013, 57),
        (1014, 49),
        (1014, 54),
        (1014, 58),
        (1015, 49),
        (1015, 54),
        (1015, 55),
        (1015, 66),
        (1016, 49),
        (1016, 54),
        (1016, 58),
        (1017, 49),
        (1018, 49),
        (1018, 54),
        (1018, 58),
        (1019, 49),
        (1019, 54),
        (1019, 58),
        (1019, 66),
        (1020, 49),
        (1020, 54),
        (1020, 58),
        (1021, 58),
        (1022, 58),
        (1023, 58),
        (1023, 56),
        (1024, 49),
        (1024, 54),
        (1024, 58),
        (1025, 49),
        (1025, 54),
        (1025, 58),
        (1034, 51),
        (1034, 49),
        (1035, 51),
        (1035, 49),
        (1040, 49),
        (1040, 54),
        (1040, 58),
        (1041, 49),
        (1041, 58),
        (1042, 49),
        (1043, 49),
        (1043, 54),
        (1043, 55),
        (1044, 58),
        (1047, 49),
        (1047, 54),
        (1047, 58),
        (1047, 55),
        (1048, 58),
        (1049, 66),
        (1051, 61),
        (1053, 57),
        (1054, 58),
        (1055, 54),
        (1056, 54),
        (1056, 57),
        (1057, 54),
        (1059, 58),
        (1059, 54),
        (1060, 49),
        (1060, 54),
        (1060, 58),
        (1061, 49),
        (1061, 54),
        (1061, 58),
        (1062, 51),
        (1062, 49),
        (1062, 54),
        (1062, 58),
        (1063, 49),
        (1063, 54),
        (1063, 58),
        (1064, 49),
        (1064, 54),
        (1064, 58),
        (1065, 49),
        (1065, 54),
        (1065, 58),
        (1066, 49),
        (1066, 54),
        (1066, 58),
        (1067, 49),
        (1067, 54),
        (1068, 49),
        (1068, 54),
        (1068, 55),
        (1069, 49),
        (1069, 54),
        (1069, 58),
        (1070, 49),
        (1072, 49),
        (1073, 49),
        (1076, 59),
        (1077, 49),
        (1079, 49),
        (1079, 54),
        (1079, 58),
        (1080, 49),
        (1081, 49),
        (1081, 54),
        (1081, 58),
        (1081, 56),
        (1082, 49),
        (1082, 58),
        (1083, 58),
        (1084, 51),
        (1084, 49),
        (1085, 49)
    """)


def downgrade() -> None:
    op.execute("DELETE FROM product_allergens WHERE product_id BETWEEN 1000 AND 1085")
    op.execute("DELETE FROM products WHERE id BETWEEN 1000 AND 1085")
    op.execute("DELETE FROM categories WHERE id BETWEEN 101 AND 107")
    # ids 1-4 (Lanches/Combos/Bebidas/Sobremesas) pertencem ao seed original
    # (seed_initial.py) — não são desfeitos por este downgrade.
